version: "3.8"

services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: core_app
    build: .
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:5000"
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
     - db
  db:
    container_name: core_db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TDYoung17!
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres-conf/postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  static_volume:
  postgres_data:
